G_loss_ramp: 15000
G_loss_scale: 0.5
KAN: false
UNet: false
batch_size: 4
borders: no_edge
checkpoints_path: ./checkpoints/
color_space: RGB
contrast_high: 1.5
contrast_low: 0.5
contrast_ramp: 1000
cuda: true
exp_name: Torch
hsv_h_scale: 1
hsv_s_scale: 1
hsv_v_scale: 5
jpeg_quality: 50
jpeg_quality_ramp: 1000
l2_edge_delay: 80000
l2_edge_gain: 10
l2_edge_ramp: 10000
l2_loss_ramp: 15000
l2_loss_scale: 2
logs_path: ./logs/
lpips_loss_ramp: 15000
lpips_loss_scale: 1.5
lr: 0.0001
min_loss: 1000
min_secret_loss: 1000
no_gan: true
no_im_loss_steps: 1500
no_jpeg: true
num_steps: 90000
pretrained: false
rnd_bri: 0.3
rnd_bri_ramp: 1000
rnd_hue: 0.1
rnd_hue_ramp: 1000
rnd_noise: 0.02
rnd_noise_ramp: 1000
rnd_sat: 1.0
rnd_sat_ramp: 1000
rnd_trans: 0.1
rnd_trans_ramp: 10000
saved_models: ./models/
secret_loss_ramp: 1
secret_loss_scale: 2.5
secret_size: 100
seed: 18
train_path: /kaggle/input/mirflickr-1m/
u_scale: 100
v_scale: 100
y_scale: 1
